import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
const root = process.argv[2] || fileURLToPath(new URL('../../../', import.meta.url)).replace(/\/$/, '');
const require = createRequire(`${root}/vd3/package.json`);
const { JSDOM } = require('jsdom');
const ts = require('typescript');
const dom = new JSDOM('<!doctype html><html><body></body></html>', { url: 'http://localhost/', pretendToBeVisual: true });
for (const key of ['window','document','DOMParser','Node','Element','HTMLElement','SVGElement','location','MutationObserver','getComputedStyle']) globalThis[key] = key === 'getComputedStyle' ? dom.window.getComputedStyle.bind(dom.window) : dom.window[key];
globalThis.requestAnimationFrame = cb => setTimeout(() => cb(0), 0);
globalThis.cancelAnimationFrame = clearTimeout;
window.matchMedia = () => ({ matches: false, addEventListener() {}, removeEventListener() {} });
let observed = 0;
globalThis.ResizeObserver = class { observe() { observed++; } unobserve() {} disconnect() {} };
const source = readFileSync(`${root}/vd3/src/utils/sanitizeHtml.ts`, 'utf8');
const compiled = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }).outputText;
const { sanitizeHtml } = await import(`data:text/javascript;base64,${Buffer.from(compiled).toString('base64')}`);
const sanitized = sanitizeHtml('<a href="/safe" onclick="window.auditMarker=1" style="position:fixed;inset:0">Example</a>');
console.log(JSON.stringify({ check: 'anchor sanitizer', sanitized, retainsHandler: sanitized.includes('onclick='), retainsStyleByDefault: sanitized.includes('style=') }));
const { mount } = await import(`${root}/vd3-flowchart/node_modules/@vue/test-utils/dist/vue-test-utils.esm-bundler.mjs`);
const { VdFlowchart } = await import(`${root}/vd3-flowchart/src/vue.js`);
const fw = mount(VdFlowchart, { props: { data: { nodes: [{id:'a',text:'Original'}], edges:[] } } });
fw.vm.getInstance().addNode({ id:'b', text:'Unsaved edit' });
const before = fw.vm.getInstance().toJSON().nodes.map(n=>n.id);
await fw.setProps({ readonly:true });
console.log(JSON.stringify({ check:'flowchart readonly toggle', before, after:fw.vm.getInstance().toJSON().nodes.map(n=>n.id) }));
fw.unmount();
const { VdChart, VdPieChart } = await import(`${root}/vd3-charts/src/vue.js`);
const chartRequire = createRequire(`${root}/vd3-charts/package.json`);
const { mount: mountChart } = chartRequire('@vue/test-utils');
for (const component of [VdChart, VdPieChart]) {
  const c = mountChart(component, { props:{type:'pie',data:[{name:'A',value:1},{name:'B',value:2}],label:'name',value:'value'} });
  console.log(JSON.stringify({check:'pie default', component:component.name, arcsPerSlice:[...c.element.querySelectorAll('path.vd-chart-slice')].map(p=>(p.getAttribute('d').match(/A/g)||[]).length)}));
  c.unmount();
}
const { BarChart } = await import(`${root}/vd3-charts/src/core.js`);
const host=document.createElement('div'); document.body.append(host);
observed=0;
const chart=BarChart({target:host,data:[{x:'A',y:1}],x:'x',y:'y',responsive:false});
chart.update({responsive:true});
console.log(JSON.stringify({check:'responsive false to true',observed}));
const oldMark=host.querySelector('rect.vd-chart-bar'); oldMark.focus();
const wasFocused=document.activeElement===oldMark;
chart.update({data:[{x:'A',y:2}]});
console.log(JSON.stringify({check:'chart redraw focus', wasFocused, oldMarkConnected:oldMark.isConnected, focusAfter:document.activeElement.tagName}));
chart.destroy();
const { VdTooltip } = await import(`${root}/vd3/dist/index.js`);
const { mount:mountCore }=require('@vue/test-utils');
const style=document.createElement('style');
style.textContent=readFileSync(`${root}/vd3/css/components/tooltips.css`,'utf8').match(/^\.vd-tooltip \{[\s\S]*?\}/m)[0];
document.head.append(style);
const tw=mountCore(VdTooltip,{attachTo:document.body,props:{text:'Help',position:'bottom'},slots:{default:'<button>Trigger</button>'}});
await tw.find('button').trigger('mouseenter');
console.log(JSON.stringify({check:'tooltip trigger wrapper',opacity:getComputedStyle(tw.element).opacity,pointerEvents:getComputedStyle(tw.element).pointerEvents,visibleTooltips:document.querySelectorAll('.vd-tooltip.is-visible').length,placementAttribute:tw.attributes('data-tooltip-placement'),positionAttribute:tw.attributes('data-tooltip-position')}));
tw.unmount();
const {defineComponent,h,ref,nextTick}=await import(`${root}/vd3-flowchart/node_modules/vue/dist/vue.runtime.esm-bundler.js`);
const reasons=[];
const Parent=defineComponent({setup(){const data=ref({nodes:[],edges:[]});return ()=>h(VdFlowchart,{data:data.value,onChange:e=>{reasons.push(e.reason);if(reasons.length<4)data.value=e.document;}});}});
const pw=mount(Parent);
pw.findComponent(VdFlowchart).vm.getInstance().addNode({text:'Trigger feedback'});
await nextTick();
console.log(JSON.stringify({check:'flowchart controlled data echo',reasons,stoppedByHarnessAt:4}));
pw.unmount();
dom.window.close();
